# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://www.professionaldev.pro/"  # Include trailing slash
title = "Professional Developer"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.

# default value is false
# read more about it: https://gohugo.io/content-management/urls/#canonicalization
# canonifyurls = true

googleAnalytics = 'G-QMH75S45WQ'

paginate = 10
disqusShortname = "professionaldev"

DefaultContentLanguage = "en"

#[taxonomies]
#category = "categories"
#tag = "tags"
#series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]

[module]
[[module.imports]]
path = 'github.com/chipzoller/hugo-clarity'


